name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - run: dotnet tool install --global dotnet-warp 
    
    - name: Create Artifact
      run: dotnet warp ./src/TattooMachineGirl.Inkbook.Data.Extract.csproj --output ./dist/ --rid -p:Version=0.1.0
    
    - uses: actions/upload-artifact@v2
      with:
        name: extract.exe
        path: ./dist
      
